version: '3.8'
services:
  ms-app:
    container_name: ms-files
    restart: always
    image: IMAGE_NAME
    ports:
      - "27193:9093"
    networks:
      - applications-network
    volumes:
      - FILES_ROOT_FOLDER:FILES_ROOT_FOLDER
    environment:
      - spring.rabbitmq.host=RABBITMQ_IP
      #- spring.rabbitmq.port=RABBITMQ_PORT
      - spring.rabbitmq.password=RABBITMQ_PASSWORD
      - spring.rabbitmq.username=APPLICATIONS_USERNAME
      - application.files.base-path=FILES_ROOT_FOLDER
networks:
  applications-network:
    external:
      name: applications-network

