version: '3.8'
services:
  ms-app:
    container_name: ms-files
    restart: always
    image: IMAGE_NAME
    ports:
      - "27192:9092"
    networks:
      - applications-network
    environment:
      - spring.rabbitmq.host=RABBITMQ_IP
      - spring.rabbitmq.port=RABBITMQ_PORT
      - spring.rabbitmq.password=RABBITMQ_PASSWORD
      - spring.rabbitmq.username=APPLICATIONS_USERNAME
networks:
  applications-network:
    external:
      name: applications-network

