server:
  port : 9093
spring:
  jackson:
    serialization:
        write-dates-as-timestamps: false
  rabbitmq:
    host: 212.83.180.65
    port: 5672
    username: rbmq_admin
    password: administrator
    virtual-host: prod-notifications
    template:
      queue: tech.files.queue
  task:
    scheduling:
        pool:
            size: 10
  application:
    name: ms-files

application:
    files:
        base-path: "/var/www/files"
