server:
  port: 9093
spring:
  data:
    mongodb:
      database: ${spring.application.name}
  jackson:
    serialization:
      write-dates-as-timestamps: false
  task:
    scheduling:
      pool:
        size: 10
  application:
    name: ms-files
